//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetAppAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choferes
    {
        public System.Guid Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> NumTaxi { get; set; }
        public string Foto { get; set; }
        public string NumTel { get; set; }
        public System.Guid Ciudad { get; set; }
        public Nullable<int> idMunicipio { get; set; }
    
        public virtual Municipio Municipio { get; set; }
    }
}
